### ISSUE TITLE
Create an options to reference Global Handlebars rather than bundle in Module

### ISSUE THREAD

**Issue by dtothefp** [altano/handlebars-loader#26]
I'm using grunt-webpack to create multiply bundles in my [current project](https://github.com/optimizely/marketing-website/blob/dfoxpowell/webpack/grunt/webpack.js).  This is a refactored architecture and has a lot of page level bundles as well as a global bundle.  Both the page and global level bundles `require` hbs templates using the handlebars-loader. The problem is that when both the global and page level bundles require hbs templates, I believe that each bundle contains Handlebars library code.  I'm not sure how efficient this is, and wondering if I can just make Handlebars available globally and pass an option to the handlebars-loader to not bundle Handlebars?

**Comment by altano** [comment]
If you're using multiple bundles in webpack you will hit this issue in many cases, not just this loader.  The correct solution is to use [webpack's CommonsChunkPlugin](https://github.com/webpack/docs/wiki/optimization#multi-page-app):

> If your entry chunks have some modules in common, there is a cool plugin for this. The CommonsChunkPlugin identifies common modules and put them into a commons chunk. You need to add two script tags to your page, one for the commons chunk and one for the entry chunk.

This will solve your issue generically, for all your modules, and not require global code.  It is a much better solution.  Good luck!

**Comment by dtothefp** [comment]
@altano I couldn't get the `CommonsChunksPlugin` working with the `handlebars-loader`. I saw your example on externals which I could use as a fallback, but I'd rather load all common chunks into a separate file.

I made this example repo using your loader and `CommonsChunksPlugin` if you have any advice.

https://github.com/dtothefp/webpack-common-chunks-hbs

**Comment by dtothefp** [comment]
@altano Nevermind, just figured it out. Had to add `handlebars` as a vendor chunk and also specify 
```js
node: {
  fs: 'empty'
}
``` 
because of errors I was getting during webpack compilation. The resulting config looks like this

```js
module.exports = {
  entry: {
    vendor: ['handlebars'],
    'bundle-with-hbs': './src/index.js',
    'no-hbs': './src/a.js',
    'with-hbs': './src/b.js'
  },

  output: {
    filename: '[name].js',
    path: path.resolve('./dist')
  },

  module: {
    loaders: [
      { test: /\.hbs$/, loader: 'handlebars-loader' }
    ]
  },

  plugins: [
    new CommonsChunkPlugin({
      name: 'vendor',
      filename: 'commons.js',
      minChunks: 0
    })
  ],

  node: {
    fs: 'empty'
  }
};
```

Hope this saves some other people with the same question some time
