### ISSUE TITLE
IE8 Error

### ISSUE THREAD

**Issue by socraticbc** [altano/handlebars-loader#28]
It looks like IE8 is choking on 'default.template' in line 192 of index.js

'default' is a reserved word in ECMA 6. tried changing it to default["template"] to no avail.

![2-12-2015-00](https://cloud.githubusercontent.com/assets/3024498/6174203/e38d9148-b2b2-11e4-9c6b-8743271fb44b.png)

![2-12-2015-01](https://cloud.githubusercontent.com/assets/3024498/6174259/2daa856a-b2b3-11e4-860e-8ff868646130.png)

**Comment by benmaurer** [comment]
I ran into the same problem and updated to version 0.1.8 -- it seems to resolve the issue

**Comment by altano** [comment]
Yes this was fixed, please let me know if you're still hitting it in the latest versions.
