### ISSUE TITLE
Custom block helpers

### ISSUE THREAD

**Issue by anthonydeaver** [altano/handlebars-loader#29]
Am I correct in assuming that the loader doesn't support customer block helpers?

**Comment by SimenB** [comment]
@altano @anthonydeaver Is this correct? Could you provide a short code sample on how to register block helpers?

**Comment by altano** [comment]
They work exactly the same as custom function helpers as far as this webpack loader is concerned:

https://github.com/altano/handlebars-loader/tree/master/examples/custom-block-helper
