### ISSUE TITLE
why must helpers be prefixed with `$` or what am I doing wrong?

### ISSUE THREAD

**Issue by gipsy-king** [altano/handlebars-loader#32]
I'm transitioning from requirejs, and my helpers are like [handlebars docs](http://handlebarsjs.com/expressions.html#helpers), they don't have a `$` prefix. But to get it to work with handlebars-loader, I would have to change all my templates to insert a `$`. I also don't understand why I have to configure both `helperDirs` and `resolve.modulesDirectories` with my helpers dir.

Changing the line [here](https://github.com/altano/handlebars-loader/blob/master/index.js#L215) from

    var request = referenceToRequest(helper.substr(1));
to

    var request = referenceToRequest(helper);

it also works, but that probably breaks something else, although the tests pass.

**Comment by altano** [comment]
Please take a look at the [helpersDir example](https://github.com/altano/handlebars-loader/blob/master/examples/helperDirs).  You only have to specify helpersDir and not moduleDirectories, and you don't have to treat helpers as modules when using helpersDir, so the `$` prefix is not required.  You only have to use `$` when you want the helper to be loaded by webpack as a module.

**Comment by gipsy-king** [comment]
I understand, that makes sense. Thank you!
