### ISSUE TITLE
external handlebars/runtime is still bundled

### ISSUE THREAD

**Issue by QuentinRoy** [altano/handlebars-loader#33]
Putting handlebars/runtime as externals does not work. The library is still bundled.

Here is a webpack.js example:
```javascript
module.exports = {
    context: __dirname + '/src',
    entry: './index.js',
    output: {
        path: __dirname + '/dist',
        filename: 'stuff.js',
        libraryTarget: 'umd',
        library: 'Stuff'
    },
    externals: [{
        // does not work :-(
        'handlebars/runtime': {
            root: 'Handlebars',
            amd: 'handlebars.runtime',
            commonjs2: 'handlebars/runtime',
            commonjs: 'handlebars/runtime'
    }],
    module: {
        loaders: [
            { test: /\.handlebars$/, loader: 'handlebars-loader' }
        ]
    }
};
```

**Comment by altano** [comment]
The [webpack documentation for externals](http://webpack.github.io/docs/configuration.html#externals) doesn't show the syntax you're using at all, so I'm not sure why you would expect it to work.  Are you using an undocumented method or something?

I just tried this and it works as expected, externalizing the runtime:

```javascript
module.exports = {
  entry: "./app.js",
  output: {
    path: "dist",
    filename: "bundle.js",
    libraryTarget: 'umd',
    library: 'App'
  },
  resolve: {
    fallback: path.join(__dirname, "helpers")
  },
	module: {
		loaders: [{ test: /\.handlebars$/, loader: __dirname + "/../../" }]
	},
  externals: [
      /handlebars.runtime/
  ]
};
```

If you are sure your method should work, please point to the webpack documentation (or source code) and explain your configuration better and I'll try to help.

**Comment by altano** [comment]
Actually I just dug a little deeper and it looks like the syntax you are using does work, it just isn't documented.

@sokra - this loader dynamically requires the handlebars runtime using an absolute path: https://github.com/altano/handlebars-loader/blob/master/index.js#L242

This code is obviously not friendly with webpack's `externals` config option as @QuentinRoy  is trying to use it, because the `externals` object literal syntax used to specify different replacements for different module systems (e.g. amd vs. commonjs) takes a string and not a regexp, so he can't do this:

```javascript
  externals: [{
      /handlebars\/runtime/: {
        root: 'Handlebars',
        amd: 'handlebars.runtime',
        commonjs2: 'handlebars/runtime',
        commonjs: 'handlebars/runtime'        
      }
  }]
```

Since this way of configuring `externals` is undocumented as far as I can tell, do you have a recommendation here for @QuentinRoy ?

**Comment by QuentinRoy** [comment]
It is kind of documented. You can find it in the [examples](https://github.com/webpack/webpack/tree/master/examples/externals).

I didn't noticed you could use regexp when not defining replacement. However, in that case I got absolute require in the UMD wrapper:
```javascript
root["MTToolbar"] = factory(root["/Users/quentin/Workspace/stuff/node_modules/handlebars/runtime.js"]);
```
It doesn't look like a good idea at all...

**Comment by altano** [comment]
In short, UMD + externals + this loader don't play nicely together and I'm not sure how to fix that.  Let's see if @sokra has an idea.

**Comment by sokra** [comment]
I think the handlebars-loader has a `runtime` query parameter...

**Comment by QuentinRoy** [comment]
Yes, but I don't think it can be used to exclue handlebars/runtime. Or at least I could not make it work..
Here is one of the things I tried:

```javascript
module.exports = {
    context: __dirname + '/src',
    entry: './index.js',
    output: {
        path: __dirname + '/dist',
        filename: 'stuff.js',
        libraryTarget: 'umd',
        library: 'Stuff'
    },
    externals: [{
        'handlebars/runtime': {
            root: 'Handlebars',
            amd: 'handlebars.runtime',
            commonjs2: 'handlebars/runtime',
            commonjs: 'handlebars/runtime'
        },
        'handlebars': {
            root: 'Handlebars',
            amd: 'Handlebars',
            commonjs: 'handlebars',
            commonjs2: 'handlebars'
        }
    ],
    module: {
        loaders: [
            { test: /\.handlebars$/, loader: 'handlebars-loader', runtime: 'handlebars/runtime' }
        ]
    }
};
```

**Comment by altano** [comment]
Thanks @sokra, I forgot that the runtime parameter would allow us to avoid the absolute path issue.

@QuentinRoy you're really close, but you can't specify loader options like that.  See http://webpack.github.io/docs/using-loaders.html#query-parameters for instructions on specifying query parameters (as regular query params or JSON), and see this example I cooked up that works:

https://github.com/altano/handlebars-loader/tree/master/examples/external-runtime

As you can see from [the output](https://github.com/altano/handlebars-loader/blob/master/examples/external-runtime/dist/bundle.js), it works and there's no handlebars runtime to be found.  You do have to handle making require("handlebars/runtime") work on your own, though.  Or whatever you make the externals config do.

**Comment by QuentinRoy** [comment]
With a bite of delay, thank you very much for your help. This is now working perfectly.
