### ISSUE TITLE
[bug] Using loader prefix without filename extension doesn't work.

### ISSUE THREAD

**Issue by trusktr** [altano/handlebars-loader#36]
For example, I have this webpack config:

```js
{
  resolve: {
    modulesDirectories: ['node_modules', 'src'],
    fallback: path.join(__dirname, 'node_modules'),
    alias: {
      'handlebars': 'handlebars/runtime.js'
    }
  },
  resolveLoader: {
    fallback: path.join(__dirname, 'node_modules'),
    alias: {
      'hbs': 'handlebars-loader'
    }
  }
}
```

so that `hbs!` is an alias for `handlebars-loader!`. Then I'm loading an AMD module that looks like this:

```js
define([
  'hbs!path/to/template'
],
function(template) {
  // ...
});
```

which results in the error

```
...
Module not found: Error: Cannot resolve module 'path/to/template' in /absolute/path/to/src/js/utils/leaflet-controls
...
```

but if I add the `.handlebars` extension, then the error will be fixed:

```js
define([
  'hbs!path/to/template.handlebars'
],
function(template) {
  // ...
});
```

The problem is that I wish not to modify the library. It's a monolithic library, and modifying it might mean breaking many RequireJS app in production. I'm trying to use this AMD library in a webpack project.

Is there a way to make it work without the extension? Do I need to supply the `loaders` array even though the `hbs!` prefix is already being used (I thought that should be enough)?

**Comment by trusktr** [comment]
Is this webpack's fault?

**Comment by altano** [comment]
Have you added .handlebars to [resolve.extensions](http://webpack.github.io/docs/configuration.html#resolve-extensions)?

**Comment by trusktr** [comment]
@altano Aah, that's it. Thank you so much!
