### ISSUE TITLE
Disable auto-inclusion of loader's Handlebars library

### ISSUE THREAD

**Issue by lostthetrail** [altano/handlebars-loader#44]
@altano 
Is there a way to stop the handlebars-loader from auto-including its compile time library, so I can include a specific version of the handlebars library for run-time usage? The specific version would be wrapped into a vendor chunk (e.g. vendor.min.js).

**Comment by altano** [comment]
You can use the `runtime` option to specify the path to a custom runtime OR you can use the webpack externals option to not bundle handlebars into your bundle (see this example https://github.com/altano/handlebars-loader/tree/master/examples/external-runtime)

**Comment by lostthetrail** [comment]
Thanks Alan. I didn't realize you could use them separated.

If I use the runtime query option by itself, I can point it at a version of handlebars I have installed in node, and only that version will be packaged?

**Comment by lostthetrail** [comment]
Confirmed working. Thanks again.

Below has been attached for anyone else looking for the same question's answer.

```javascript
module.exports = {
    'entry': {
        'vendor': [
            'handlebars'
        ]
    },
    'resolve': {
        'alias': {
            'handlebars': 'handlebars/dist/handlebars.runtime.js',
        },
        'extensions': ['', '.hbs', '.js'],
    },
    'module': {
        'loaders': [
            {
                test: /\.hbs$/,
                loader: 'handlebars-loader',
                query: {
                    runtime: 'handlebars'
                }
            }
        ]
    }
}
```
