### ISSUE TITLE
Can I register an block helper in normal way?

### ISSUE THREAD

**Issue by littlee** [altano/handlebars-loader#48]
Can I register an block helper just using the code below?
```js
Handlebars.registerHelper('hello', function(str) {
	return 'hello'';
});
```

**Comment by JSteunou** [comment]
You have to register on Handlebars/runtime because your preCompiled template will run against it

```
var Hbs = require('Handlebars/runtime');
Hbs.registerHelper(...);
```

**Comment by altano** [comment]
If you do this, you're not setting up a dependency between the module that will use the helper and the module that contains the helper.  You're circumventing webpack completely.  If you want to see how to do it correctly, look at this example: https://github.com/altano/handlebars-loader/tree/master/examples/custom-block-helper

**Comment by littlee** [comment]
I know there is handlebars-loader,
but this loader can not work with webpack-i18n-plugin's __() function.
I couldn't write some code like:
```html
<h1>__('title')</h1>
```
and make 'title' i18n.

**Comment by altano** [comment]
I'm not familiar with that plugin and how it works. Not sure why it isn't compatible.  You could feed the localized string as data into the template function instead of localizing the string in the template.

**Comment by littlee** [comment]
> feed the localized string as data
may be a solution.

**Comment by sidonaldson** [comment]
If you do want to pass in data as JSON you can do it like this:

```
new HtmlWebpackPlugin({
    data: {title: 'New Page!'}
})
```

it's then available via:
```
<title>{{htmlWebpackPlugin.options.data.title}}</title>
```

Found this wasn't really documented that well so I hope this is useful. You can even pass in the same object the i18n plugin uses as it's not bundled.
