### ISSUE TITLE
[question] How can I require Handlebars, the same the loader is using...

### ISSUE THREAD

**Issue by JSteunou** [altano/handlebars-loader#53]
... because I'm moving to webpack using old source code I cannot update, and the way I load my handlebars helpers before was manual, like

```js
var Handlebars = require('Handlebars');
Handlebars.registerHelper('name', function() {});
```
And at the beginning of my app I had a call to a module which load all my helpers.

When I try this way of doing with webpack + this loader, I does not seem to load the same instance of Handlebars, and I have warning & errors like in #31

**Comment by JSteunou** [comment]
Answering myself, I need to use handlebars/runtime to manually register my helpers. I now need to find how create an alias for handlebars only for my modules in order to not mess without the loader which require the actual handlebars.

**Comment by JSteunou** [comment]
Ok, just aliasing handlebars by handlebars/runtime works and this do not mess with the loader.

**Comment by rrawat-dev** [comment]
> Ok, just aliasing handlebars by handlebars/runtime works and this do not mess with the loader.

Could you please provide the syntax.
