### ISSUE TITLE
Getting function text instead of compiled template

### ISSUE THREAD

**Issue by craigjennings11** [altano/handlebars-loader#61]
I've got a webpack.config.js file that has this,

```js
module: {
  loaders: [{
    loader: 'handlebars-loader',
    query: { helperDirs: helperDirs },
    test: /\.hbs$/,
  }],
},
resolveLoader: {
  alias: { hbs: 'handlebars-loader' },
  root: [path.join(__dirname, 'node_modules')],
},
```

When I import the template via requirejs-style like this,

```js
define(['hbs!templates/header/headerTpl'], function(headerTpl) {...});
```

the resulting `headerTpl` is a function, but when executed returns weird function text instead of a compiled template. For example, `headerTpl()` returns something like

> var Handlebars = require("c:\\project\\node_modules\\handlebars\\runtime.js");
module.exports = (Handlebars["default"] || Handlebars).template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div id=\"global-nav\" class=\"navbar navbar-fixed-top fw-light\">\r\n</div>\r\n";
},"useData":true});"

Am I missing something?

**Comment by craigjennings11** [comment]
Turns out I was running the templates through the loader twice. Once via `hbs!` and then again through the loader definition with a test of `/\.hbs$/`. Removing `hbs!` from my requires fixes this. However, I'd rather not have to go through and change all of my requires to no longer have `hbs!` if possible. Is there a way to pass query strings to a resolve loader alias? Something like 
```js
alias: { hbs: 'handlebars-loader?helperDirs[]=path/to/helpers' },
```

**Comment by eddiemoore** [comment]
Hey @craigjennings11 Did you manage to find a way of doing this without having to change all the `hbs!` references?

**Comment by craigjennings11** [comment]
I didn't. I ended up just doing a find/replace in my project of `hbs!` to nothing.

**Comment by eddiemoore** [comment]
Hmm. OK thanks. I'm facing the same issue now. Didn't really want to have to change the thousands of files we have.
