### ISSUE TITLE
is there any options to minify handlebars?

### ISSUE THREAD

**Issue by keenwon** [altano/handlebars-loader#72]
![image](https://cloud.githubusercontent.com/assets/5516478/11773184/450964f8-a261-11e5-82df-fac6c3514e72.png)

is there any options to remove those spaces?

**Comment by ignoreswing** [comment]
+1
I have the same problem!

**Comment by keenwon** [comment]
I now use Jade

**Comment by SimenB** [comment]
Whitespace is upstream handlebars, nothing to do with this loader.

handlebars.js#336

**Comment by keenwon** [comment]
Template whitespace may be omitted from either side of any mustache statement by adding a `~` character by the braces.

```handlebars
{{#each nav ~}}
  <a href="{{url}}">
    {{~#if test}}
      {{~title}}
    {{~^~}}
      Empty
    {{~/if~}}
  </a>
{{~/each}}
```
with this context:
```javascript
{
  nav: [
    {url: 'foo', test: true, title: 'bar'},
    {url: 'bar'}
  ]
}
```
results in output sans newlines and formatting whitespace:
```html
<a href="foo">bar</a><a href="bar">Empty</a>
```

**Comment by ignoreswing** [comment]
Hi, SimenB & Keenwon

Thank you for your prompt reply and helpful suggestion.
"Give expression a ~" is undoubtedly a good solution.
However, it is too tedious to add every handlebar expression with a '~', i.e., {{~  ~}}.

I found a [html-minify plugin] (https://github.com/jney/grunt-htmlcompressor) which can minify my .hbs code without breaking it. It is based on [htmlcompressor] (https://code.google.com/archive/p/htmlcompressor)
In my production mode, my goal is very simple:
* Remove all html comments (e.g., )
* Remove all blanks and new lines

My grunt config is set to:
```javascript
grunt task:
	grunt.initConfig({
		htmlcompressor: {
		   compile: {
		       expand: true,
		       src   : ['src/templates/**/*.html'],
		       dest  : 'compressed',
		       options: {
		           type                   : 'html',
		           preserveServerScript   : true,
		           removeQuotes           : true,  //Remove unneeded quotes
		           removeIntertagSpaces   : true,
		           removeSurroundingSpaces: 'min',
		           preserve               : 'custom.hbs.rule'
		       }
		   }
		},
	});
```
and custom.hbs.rule (a skipped regular expression) is
```
	\{\{[^}]+\}\}
	\{\{\{[^}]+\}\}\}
```

After compression, the compressed hbs code looks like this
![2016-01-26 16 17 49](https://cloud.githubusercontent.com/assets/5887478/12576073/2766ce60-c44c-11e5-9f88-8c4c593cca03.png)

I can easily change my webpack config to load the compressed code, says,
```
    resolve: {
        alias: {
            'templates'     : __dirname + '/src/templates',           //development mode
            //'templates'   : __dirname + '/compressed/src/templates',//production mode
        }
    },
```
Alought the plugin cannot support hot module replacement for webpack, it's good enough for me.

**Comment by attenzione** [comment]
https://github.com/pcardune/handlebars-loader/issues/46#issuecomment-485843595
