### ISSUE TITLE
官网的example 例子都 运行不起来 报 ERROR in Cannot find module 'handlebars' 的错

### ISSUE THREAD

**Issue by yangfeiloveG** [altano/handlebars-loader#76]

**Comment by 121onto** [comment]
Same Error here.  Did you track down the cause?

**Comment by 121onto** [comment]
I fixed this issue by installing handlebars:

```bash
npm -i handlebars --save-dev
```

**Comment by alankyshum** [comment]
It would be great if @yangfeiloveG can change this to English so that more people having the same issue could find the answers to it.

Thanks.

**Comment by atav32** [comment]
@yangfeiloveG 请你把主题翻译一成: 

> Running the example on the official website throws `ERROR: Cannot find module 'handlebars'`

**Comment by atav32** [comment]
@121onto I believe there's a slight typo

I use

```
npm i -D handebars
```
